project_id = "lxpqrfsdfgnbndpekoaj"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000000

[db]
port = 54322

[db.seed]
enabled = true
sql_paths = ['./seed.sql']

[realtime]
enabled = true

[studio]
port = 54323
